/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cristiano_ronaldo.glb --transform 
Files: cristiano_ronaldo.glb [10.65MB] > /Users/yandingyin/Desktop/portfolio/public/models/cristiano_ronaldo-transformed.glb [1.89MB] (82%)
Author: aleganda (https://sketchfab.com/aleganda)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cristiano-ronaldo-710d1b01b0624135861feb3f0bb7048a
Title: cristiano ronaldo
*/

import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Cristiano(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/cristiano_ronaldo-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(()=>{
    actions["Armature.001Action.001"].play()
  },[actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.uniform} skeleton={nodes.Object_7.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.legs} skeleton={nodes.Object_8.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.boots} skeleton={nodes.Object_9.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material} skeleton={nodes.Object_10.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.face} skeleton={nodes.Object_11.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.eyelash} skeleton={nodes.Object_12.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.eyes} skeleton={nodes.Object_13.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
        <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.hair} skeleton={nodes.Object_14.skeleton} rotation={[-Math.PI, 0, -Math.PI]} scale={0.971} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/cristiano_ronaldo-transformed.glb')
