/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 animated_ecuadorian_flag.glb --transform 
Files: animated_ecuadorian_flag.glb [15.96MB] > /Users/yandingyin/Desktop/portfolio/public/models/animated_ecuadorian_flag-transformed.glb [12.95MB] (19%)
Author: VHM777 (https://sketchfab.com/gizacorp01)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-ecuadorian-flag-1bf249c4dd654fbd96ba296a9720b64c
Title: Animated Ecuadorian Flag
*/

import React, {useEffect} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ecuador(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/animated_ecuadorian_flag-transformed.glb')
  const { actions, names } = useAnimations(animations, group)

useEffect(() => {
  actions['Object_0'].play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Emptyrotation_1" rotation={[0, 0.004, 0]} />
        </group>
        <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} scale={0} />
        <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.M_BASE} scale={0} />
        <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Silver} scale={0.696} />
        <mesh name="mesh_1" geometry={nodes.mesh_1.geometry} material={materials.M_FLAG} morphTargetDictionary={nodes.mesh_1.morphTargetDictionary} morphTargetInfluences={nodes.mesh_1.morphTargetInfluences} scale={0} />
        <mesh name="mesh_3" geometry={nodes.mesh_3.geometry} material={materials.E_FLAG} morphTargetDictionary={nodes.mesh_3.morphTargetDictionary} morphTargetInfluences={nodes.mesh_3.morphTargetInfluences} scale={0.696} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/animated_ecuadorian_flag-transformed.glb')
