/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 goku.glb 
Author: Nemix (https://sketchfab.com/nemix)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/goku-6a79ab6b70b747b68e787da1458ab582
Title: Goku
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Goku(props) {
  const { nodes, materials } = useGLTF('./models/goku.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} position={[-0.019, 0, -0.013]} rotation={[-Math.PI / 2, 0, 2.999]} />
    </group>
  )
}

useGLTF.preload('./models/goku.glb')
