/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 homelander_-_the_boys.glb --transform 
Files: homelander_-_the_boys.glb [15.3MB] > /Users/yandingyin/Desktop/portfolio/public/models/homelander_-_the_boys-transformed.glb [2MB] (87%)
Author: Alvaro Ramirez (https://sketchfab.com/alvaro_ramirez)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/homelander-the-boys-3bb2b0e202b5427387326b501901a722
Title: Homelander - The Boys
*/

import React, {use, useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Homelander(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/homelander_-_the_boys-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions["Armature|ArmatureAction"].play()
  })
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Material_40} skeleton={nodes.Object_72.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_73" geometry={nodes.Object_73.geometry} material={materials.Material_39} skeleton={nodes.Object_73.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Material_38} skeleton={nodes.Object_74.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.Material_36} skeleton={nodes.Object_75.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.Material_42} skeleton={nodes.Object_76.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.Material_41} skeleton={nodes.Object_77.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.Material_37} skeleton={nodes.Object_78.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.eyeglow} skeleton={nodes.Object_79.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/homelander_-_the_boys-transformed.glb')
