/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 old_juggernog_-_call_of_duty_perk_machine.glb --transform 
Files: old_juggernog_-_call_of_duty_perk_machine.glb [6.76MB] > /Users/yandingyin/Desktop/portfolio/public/models/old_juggernog_-_call_of_duty_perk_machine-transformed.glb [676.94KB] (90%)
Author: Jamie McFarlane (https://sketchfab.com/jamiemcfarlane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-juggernog-call-of-duty-perk-machine-0d8abe67a62a4823a0b418a1fb395502
Title: Old Juggernog - Call of Duty Perk Machine
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Jugger(props) {
  const { nodes, materials } = useGLTF('/models/old_juggernog_-_call_of_duty_perk_machine-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Front_Piece_Mat} />
      <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Jug_Base_Mat} />
    </group>
  )
}

useGLTF.preload('/models/old_juggernog_-_call_of_duty_perk_machine-transformed.glb')

