/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 kame_house.glb --transform 
Files: kame_house.glb [21.61MB] > /Users/yandingyin/Desktop/portfolio/public/models/kame_house-transformed.glb [2.43MB] (89%)
Author: madziam (https://sketchfab.com/madziam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kame-house-f055f8adf89c4d1280b2bfa8edb49a7c
Title: Kame House
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Kame(props) {
  const { nodes, materials } = useGLTF('/models/kame_house-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.island_grass_0.geometry} material={materials.grass} position={[0.003, -0.03, 0.007]} scale={0.011} />
      <mesh geometry={nodes.island_sand_0.geometry} material={materials.sand} position={[0.003, -0.03, 0.007]} scale={0.011} />
      <mesh geometry={nodes.water_water_0.geometry} material={materials.water} position={[0.003, -0.8, 0.007]} scale={0.011} />
      <mesh geometry={nodes.rock001_rock_0.geometry} material={materials.rock} position={[5.278, -0.159, 3.938]} scale={0.011} />
      <mesh geometry={nodes.house_hause_0.geometry} material={materials.hause} position={[0.003, 1.623, 0.007]} scale={0.011} />
      <mesh geometry={nodes.roof_roof_0.geometry} material={materials.roof} position={[-0.809, 4.34, -0.055]} scale={0.011} />
      <mesh geometry={nodes.stairs_wood_0.geometry} material={materials.wood} position={[1.62, 0.011, 3.7]} scale={0.011} />
      <mesh geometry={nodes.window_front_white_window_wood_0.geometry} material={materials.white_window_wood} position={[-2.323, 1.825, 2.645]} scale={0.011} />
      <mesh geometry={nodes.window_front_windows_0.geometry} material={materials.windows} position={[-2.323, 1.825, 2.645]} scale={0.011} />
      <mesh geometry={nodes.door_door_0.geometry} material={materials.door} position={[0.003, 1.623, 0.007]} scale={0.011} />
      <mesh geometry={nodes.door_door_inside_0.geometry} material={materials.door_inside} position={[0.003, 1.623, 0.007]} scale={0.011} />
      <mesh geometry={nodes.wind_gauge_metal_0.geometry} material={materials.metal} position={[0.003, 6.206, 2.353]} scale={0.011} />
      <mesh geometry={nodes.dragon_ball_Sphere_dragon_balls_0.geometry} material={materials.dragon_balls} position={[-6.813, -0.091, 6.094]} scale={0.011} />
      <mesh geometry={nodes.star_star_0.geometry} material={materials.star} position={[-6.812, -0.086, 6.093]} rotation={[Math.PI / 2, 0, 0.398]} scale={0} />
      <mesh geometry={nodes.trunk001_trunk001_0.geometry} material={materials['trunk.001']} position={[6.919, -0.302, -5.892]} rotation={[-1.086, -1.392, -1.245]} scale={0.005} />
      <mesh geometry={nodes.trunk001_leaf001_0.geometry} material={materials['leaf.001']} position={[6.919, -0.302, -5.892]} rotation={[-1.086, -1.392, -1.245]} scale={0.005} />
      <mesh geometry={nodes.lezak_Material_0.geometry} material={materials.Material} position={[-3.779, -0.121, 4.624]} rotation={[-Math.PI, 1.108, -Math.PI]} scale={0.015} />
    </group>
  )
}

useGLTF.preload('/models/kame_house-transformed.glb')
