/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 luffy_-_one_piece.glb --transform 
Files: luffy_-_one_piece.glb [2.13MB] > /Users/yandingyin/Desktop/portfolio/public/models/luffy_-_one_piece-transformed.glb [404.71KB] (81%)
Author: CreadorDeMu (https://sketchfab.com/creadordemu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/luffy-one-piece-44b58336c7344f058a02c6944b7ad843
Title: Luffy - One Piece
*/

import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Luffy(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/luffy_-_one_piece-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Idle'].play()
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials['Material.001']} skeleton={nodes.Object_7.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.016} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.001']} skeleton={nodes.Object_9.skeleton} rotation={[Math.PI / 2, 0, 0]} scale={0.016} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/luffy_-_one_piece-transformed.glb')
