/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mono_bomba_-_call_of_duty.glb --transform 
Files: mono_bomba_-_call_of_duty.glb [10.86MB] > /Users/yandingyin/Desktop/portfolio/public/models/mono_bomba_-_call_of_duty-transformed.glb [1.68MB] (85%)
Author: DanixsDesigner (https://sketchfab.com/DanixsDesigner4774)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mono-bomba-call-of-duty-49c88021414744af8ca53a79e46fe072
Title: Mono Bomba - Call Of Duty
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/mono_bomba_-_call_of_duty-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.mtl_wpn_t7_zmb_monkey_clothes_lowres} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.mtl_wpn_t7_zmb_monkey_fur_lowres} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.mtl_wpn_t7_zmb_monkey_light_lowres} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.mtl_wpn_t7_zmb_monkey_lowres} rotation={[-Math.PI, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.mtl_wpn_t7_zmb_monkey_metal_lowres} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/mono_bomba_-_call_of_duty-transformed.glb')
