/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 mordecai__regular_show.glb --transform 
Files: mordecai__regular_show.glb [4.09MB] > /Users/yandingyin/Desktop/portfolio/public/models/mordecai__regular_show-transformed.glb [333.34KB] (92%)
Author: metekrts (https://sketchfab.com/metekrts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mordecai-regular-show-156a1e61b1144cebab657abb575c8f73
Title: Mordecai || Regular Show
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Mordecai(props) {
  const { scene } = useGLTF('./models/mordecai__regular_show-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials['Mordecai_-_Base']} skeleton={nodes.Object_7.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials['Mordecai_-_Blue']} skeleton={nodes.Object_9.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials['Mordecai_-_Blue']} skeleton={nodes.Object_11.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials['Mordecai_-_Black']} skeleton={nodes.Object_12.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials['Mordecai_-_Gray']} skeleton={nodes.Object_14.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials['Mordecai_-_Black']} skeleton={nodes.Object_15.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_85.geometry} material={materials['Mordecai_-_White']} skeleton={nodes.Object_85.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_86.geometry} material={materials['Mordecai_-_Black']} skeleton={nodes.Object_86.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_88.geometry} material={materials['Mordecai_-_Blue']} skeleton={nodes.Object_88.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_90.geometry} material={materials['Mordecai_-_White']} skeleton={nodes.Object_90.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
      <skinnedMesh geometry={nodes.Object_91.geometry} material={materials['Mordecai_-_Black']} skeleton={nodes.Object_91.skeleton} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/mordecai__regular_show-transformed.glb')
