/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 naruto_rage.glb --transform 
Files: naruto_rage.glb [1.89MB] > /Users/yandingyin/Desktop/portfolio/public/models/naruto_rage-transformed.glb [309.3KB] (84%)
Author: kiritouJert (https://sketchfab.com/Thekiritou.Fr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/naruto-rage-3960097528924a83be348d9d59995ed8
Title: Naruto Rage
*/

import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Naruto(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/naruto_rage-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.C__Users_JK_Desktop_NARUTO_ULTI} skeleton={nodes.Object_86.skeleton} position={[-0.011, 0, 0]} scale={0.013} />
        <skinnedMesh name="Object_87" geometry={nodes.Object_87.geometry} material={materials.C__Users_JK_Desktop_NARUTO_ULTI0} skeleton={nodes.Object_87.skeleton} position={[-0.011, 0, 0]} scale={0.013} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/naruto_rage-transformed.glb')
