/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 omni_man_fortnite.glb --transform 
Files: omni_man_fortnite.glb [4.02MB] > /Users/yandingyin/Desktop/portfolio/public/models/omni_man_fortnite-transformed.glb [519KB] (87%)
Author: Soccerbro987 (https://sketchfab.com/Soccerbro987)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/omni-man-fortnite-20d7236f54f942d2a1d339afa20ef2e4
Title: Omni_man_fortnite
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function OmniMan(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/omni_man_fortnite-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <mesh name="Object_113" geometry={nodes.Object_113.geometry} material={materials.Material} position={[0.078, -12.456, -1.542]} rotation={[-0.003, -0.019, -0.002]} scale={22.492} />
        <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.002']} skeleton={nodes.Object_92.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_95" geometry={nodes.Object_95.geometry} material={materials.material_0} skeleton={nodes.Object_95.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} skeleton={nodes.Object_98.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials['Material.004']} skeleton={nodes.Object_101.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.003']} skeleton={nodes.Object_104.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_107" geometry={nodes.Object_107.geometry} material={materials['Material.006']} skeleton={nodes.Object_107.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
        <skinnedMesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.005']} skeleton={nodes.Object_110.skeleton} position={[-0.02, 0.257, 0.385]} scale={19.983} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/omni_man_fortnite-transformed.glb')
