/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pikachu.glb --transform 
Files: pikachu.glb [1.88MB] > /Users/yandingyin/Desktop/portfolio/public/models/pikachu-transformed.glb [375.8KB] (80%)
Author: Raghav Gupta (https://sketchfab.com/raghav-wd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pikachu-37c740f674cd4719a1d1d2970bbe8c30
Title: Pikachu
*/

import React, {useEffect} from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Pikachu(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/pikachu-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions['Dance'].play()
  },[actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Material_160} skeleton={nodes.Object_7.skeleton} position={[0.006, -0.018, -0.048]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} skeleton={nodes.Object_8.skeleton} position={[0.006, -0.018, -0.048]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Material.003']} skeleton={nodes.Object_9.skeleton} position={[0.006, -0.018, -0.048]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.002']} skeleton={nodes.Object_10.skeleton} position={[0.006, -0.018, -0.048]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/pikachu-transformed.glb')
