/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ray_gun_v1.glb --transform 
Files: ray_gun_v1.glb [1.14MB] > /Users/yandingyin/Desktop/portfolio/public/models/ray_gun_v1-transformed.glb [84.04KB] (93%)
Author: dev-shawn (https://sketchfab.com/dev-shawn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ray-gun-v1-fbbb221cb97f4e92a898e9b704e2c774
Title: Ray Gun v1
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/ray_gun_v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} position={[0.116, -0.075, -2.179]} rotation={[0, 0, -Math.PI / 2]} scale={[1.109, 0.835, 1.155]} />
    </group>
  )
}

useGLTF.preload('/models/ray_gun_v1-transformed.glb')
