/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rickmorty2.glb --transform 
Files: rickmorty2.glb [28.14MB] > /Users/yandingyin/Desktop/portfolio/public/models/rickmorty2-transformed.glb [2.06MB] (93%)
Author: pARkesy84 (https://sketchfab.com/pARkesy84)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rick-and-morty-3ac793cf529647f6b08828ef16fd5b41
Title: Rick and Morty
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RickMorty(props) {
  const { nodes, materials } = useGLTF('./models/rickmorty2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('./models/rickmorty2-transformed.glb')
