/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rigby_3d.glb --transform 
Files: rigby_3d.glb [2.15MB] > /Users/yandingyin/Desktop/portfolio/public/models/rigby_3d-transformed.glb [189.64KB] (91%)
Author: Bproductions (https://sketchfab.com/beytckr1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rigby-3d-2402f6e890dd4340aa577f54cc4b6f01
Title: RİGBY 3D
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Rigby(props) {
  const { nodes, materials } = useGLTF('./models/rigby_3d-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.BezierCurve_Material004_0.geometry} material={materials['Material.004']} position={[-0.011, -0.168, -1.17]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.BezierCurve_Material_0.geometry} material={materials.Material} position={[-0.011, -0.168, -1.17]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube_Material002_0.geometry} material={materials['Material.002']} position={[-0.001, -0.905, 0.126]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere001_Material006_0.geometry} material={materials['Material.006']} position={[0.005, 0.325, 0.783]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} position={[-0.001, 0.036, 0.32]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Sphere003_Material003_0.geometry} material={materials['Material.003']} position={[-0.004, -0.07, 0.109]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/rigby_3d-transformed.glb')
