/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 maestro_muten__master_roshi.glb --transform 
Files: maestro_muten__master_roshi.glb [13.27MB] > /Users/yandingyin/Desktop/portfolio/public/models/maestro_muten__master_roshi-transformed.glb [1.33MB] (90%)
Author: Amerigo Giorgetti (https://sketchfab.com/Amerigo_Giorgetti)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/maestro-muten-master-roshi-eacbfdd27d50475d86f1b84ea5a34678
Title: maestro Muten / master Roshi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Roshi(props) {
  const { nodes, materials } = useGLTF('./models/maestro_muten__master_roshi-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.corpo_hp_copy1_corpo_hp_copy1_0.geometry} material={materials.corpo_hp_copy1} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.occhiali_lp_occhiali_lp_0.geometry} material={materials.occhiali_lp} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.occhi_fatto_lp_occhi_fatto_lp_0.geometry} material={materials.occhi_fatto_lp} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.barba_lp_barba_lp_0.geometry} material={materials.barba_lp} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.corpo_hp_copy2_corpo_hp_copy2_0.geometry} material={materials.corpo_hp_copy2} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.guscio_lp_guscio_lp_0.geometry} material={materials.guscio_lp} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.corpo_hp_copy3_corpo_hp_copy3_0.geometry} material={materials.corpo_hp_copy3} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.corpo_hp_copy4_corpo_hp_copy4_0.geometry} material={materials.corpo_hp_copy4} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.scarpe_lp_scarpe_lp_0.geometry} material={materials.scarpe_lp} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.PM3D_Sphere3D1_1_PM3D_Sphere3D1_1_0.geometry} material={materials.PM3D_Sphere3D1_1} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
      <mesh geometry={nodes.PolyMesh3D1_3_PolyMesh3D1_3_0.geometry} material={materials.PolyMesh3D1_3} position={[-0.01, 0.015, 0]} rotation={[0, 0, 0.16]} />
    </group>
  )
}

useGLTF.preload('./models/maestro_muten__master_roshi-transformed.glb')
