/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 camp_nou_stadium.glb 
Author: farhad.Guli (https://sketchfab.com/farhad.Guli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/camp-nou-stadium-37c9bfbd9ee64b90bd67ab7f500317e1
Title: Camp Nou Stadium
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Stadium(props) {
  const { nodes, materials } = useGLTF('/models/camp_nou_stadium.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-4455.959, -4800.122, 161.444]}>
          <mesh geometry={nodes.Material2.geometry} material={materials.cn_r1} />
          <mesh geometry={nodes.Material2_1.geometry} material={materials.cn_f}/>

          <mesh geometry={nodes.Material3.geometry} material={materials.cn_f_0} />

          <mesh geometry={nodes.Material4.geometry} material={materials.cn_f_1} />
          <mesh geometry={nodes.Material5.geometry} material={materials.cn_f_2} />
          <mesh geometry={nodes.Material6.geometry} material={materials.cn_f_3} />
          <mesh geometry={nodes.Material7.geometry} material={materials.cn_f_4} />
          <mesh geometry={nodes.Material8.geometry} material={materials.cn_f_5} />
          <mesh geometry={nodes.Material9.geometry} material={materials.cn_f_6} />
          <mesh geometry={nodes.Material10.geometry} material={materials.cn_f_7} />
          <mesh geometry={nodes.Material11.geometry} material={materials.cn_f_8} />
          <mesh geometry={nodes.Material2_2.geometry} material={materials.cnscf2} />
          <mesh geometry={nodes.Material3_1.geometry} material={materials.cnscf2_9} />
          <mesh geometry={nodes.Material4_1.geometry} material={materials.cnscf2_10} />
          <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_4.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_5.geometry} material={materials.cn_r1} />
          <mesh geometry={nodes.Material3_2.geometry} material={materials.cn_r1_11} />
          <mesh geometry={nodes.Material4_2.geometry} material={materials.cn_r1_12} />
          <mesh geometry={nodes.Material5_1.geometry} material={materials.cn_r1_13} />
          <mesh geometry={nodes.Material6_1.geometry} material={materials.cn_r1_14} />
          <mesh geometry={nodes.Material7_1.geometry} material={materials.cn_r1_15} />
          <mesh geometry={nodes.Material8_1.geometry} material={materials.cn_r1_16} />
          <mesh geometry={nodes.Material9_1.geometry} material={materials.cn_r1_17} />
          <mesh geometry={nodes.Material10_1.geometry} material={materials.cn_r1_18} />
          <mesh geometry={nodes.Material11_1.geometry} material={materials.cn_r1_19} />
          <mesh geometry={nodes.Material12.geometry} material={materials.cn_r1_20} />
          <mesh geometry={nodes.Material13.geometry} material={materials.cn_r1_21} />
          <mesh geometry={nodes.Material14.geometry} material={materials.cn_r1_22} />
          <mesh geometry={nodes.Material15.geometry} material={materials.cn_r1_23} />
          <mesh geometry={nodes.Material16.geometry} material={materials.cn_r1_24} />
          <mesh geometry={nodes.Material17.geometry} material={materials.cn_r1_25} />
          <mesh geometry={nodes.Material18.geometry} material={materials.cn_r1_26} />
          <mesh geometry={nodes.Material19.geometry} material={materials.cn_r1_27} />
          <mesh geometry={nodes.Material20.geometry} material={materials.cn_r1_28} />
          <mesh geometry={nodes.Material2_6.geometry} material={materials.cn_bs} />
          <mesh geometry={nodes.Material3_3.geometry} material={materials.cn_bs_29} />
          <mesh geometry={nodes.Material4_3.geometry} material={materials.cn_bs_30} />
          <mesh geometry={nodes.Material5_2.geometry} material={materials.cn_bs_31} />
          <mesh geometry={nodes.Material6_2.geometry} material={materials.cn_bs_32} />
          <mesh geometry={nodes.Material2_7.geometry} material={materials.cn_wt} />
          <mesh geometry={nodes.Material2_8.geometry} material={materials.cn_rt} />
          <mesh geometry={nodes.Material2_9.geometry} material={materials.cn_bbs} />
          <mesh geometry={nodes.Material3_4.geometry} material={materials.cn_bbs_33} />
          <mesh geometry={nodes.Material4_4.geometry} material={materials.cn_bbs_34} />
          <mesh geometry={nodes.Material5_3.geometry} material={materials.cn_bbs_35} />
          <mesh geometry={nodes.Material2_10.geometry} material={materials.cn_r2} />
          <mesh geometry={nodes.Material2_11.geometry} material={materials.cn_rs} />
          <mesh geometry={nodes.Material3_5.geometry} material={materials.cn_rs_36} />
          <mesh geometry={nodes.Material4_5.geometry} material={materials.cn_rs_37} />
          <mesh geometry={nodes.Material5_4.geometry} material={materials.cn_rs_38} />
          <mesh geometry={nodes.Material2_12.geometry} material={materials.cn_et} />
          <mesh geometry={nodes.Material2_13.geometry} material={materials.cn_rs_37} />
          <mesh geometry={nodes.Material3_6.geometry} material={materials.cn_rs_39} />
          <mesh geometry={nodes.Material4_6.geometry} material={materials.cn_rs_40} />
          <mesh geometry={nodes.Material5_5.geometry} material={materials.cn_rs_41} />
          <mesh geometry={nodes.Material2_14.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_15.geometry} material={materials.cn_fb} />
          <mesh geometry={nodes.Material3_7.geometry} material={materials.cn_bs_42} />
          <mesh geometry={nodes.Material2_16.geometry} material={materials.cn_bs_29} />
          <mesh geometry={nodes.Material4_7.geometry} material={materials.cn_bs_43} />
          <mesh geometry={nodes.Material5_6.geometry} material={materials.cn_bs_44} />
          <mesh geometry={nodes.Material6_3.geometry} material={materials.cn_bs_45} />
          <mesh geometry={nodes.Material7_2.geometry} material={materials.cn_bs_46} />
          <mesh geometry={nodes.Material8_2.geometry} material={materials.cn_bs_47} />
          <mesh geometry={nodes.Material2_17.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_18.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_19.geometry} material={materials.cn_rs_37} />
          <mesh geometry={nodes.Material3_8.geometry} material={materials.cn_rs_48} />
          <mesh geometry={nodes.Material4_8.geometry} material={materials.cn_rs_49} />
          <mesh geometry={nodes.Material5_7.geometry} material={materials.cn_rs_50} />
          <mesh geometry={nodes.Material6_4.geometry} material={materials.cn_rs_51} />
          <mesh geometry={nodes.Material7_3.geometry} material={materials.cn_rs_52} />
          <mesh geometry={nodes.Material8_3.geometry} material={materials.cn_rs_53} />
          <mesh geometry={nodes.Material9_2.geometry} material={materials.cn_rs_54} />
          <mesh geometry={nodes.Material10_2.geometry} material={materials.cn_rs_55} />
          <mesh geometry={nodes.Material2_20.geometry} material={materials.cn_bs_29} />
          <mesh geometry={nodes.Material2_21.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_22.geometry} material={materials.cn_fcb} />
          <mesh geometry={nodes.Material3_9.geometry} material={materials.cn_fcb_56} />
          <mesh geometry={nodes.Material4_9.geometry} material={materials.cn_fcb_57} />
          <mesh geometry={nodes.Material5_8.geometry} material={materials.cn_fcb_58} />
          <mesh geometry={nodes.Material2_23.geometry} material={materials.cn_mqc} />
          <mesh geometry={nodes.Material3_10.geometry} material={materials.cn_mqc_59} />
          <mesh geometry={nodes.Material2_24.geometry} material={materials.cn_fb} />
          <mesh geometry={nodes.Material2_25.geometry} material={materials.cn_fb} />
          <mesh geometry={nodes.Material2_26.geometry} material={materials.cnscf2} />
          <mesh geometry={nodes.Material2_27.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_28.geometry} material={materials.cn_rs_37} />
          <mesh geometry={nodes.Material3_11.geometry} material={materials.cn_rs_60} />
          <mesh geometry={nodes.Material4_10.geometry} material={materials.cn_rs_61} />
          <mesh geometry={nodes.Material5_9.geometry} material={materials.cn_rs_62} />
          <mesh geometry={nodes.Material6_5.geometry} material={materials.cn_rs_63} />
          <mesh geometry={nodes.Material7_4.geometry} material={materials.cn_rs_64} />
          <mesh geometry={nodes.Material8_4.geometry} material={materials.cn_rs_65} />
          <mesh geometry={nodes.Material9_3.geometry} material={materials.cn_rs_66} />
          <mesh geometry={nodes.Material10_3.geometry} material={materials.cn_rs_67} />
          <mesh geometry={nodes.Material2_29.geometry} material={materials.cn_fb} />
          <mesh geometry={nodes.Material2_30.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_31.geometry} material={materials.cn_scb} />
          <mesh geometry={nodes.Material2_32.geometry} material={materials.cn_bs_29} />
          <mesh geometry={nodes.Material2_33.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_34.geometry} material={materials.Color_000} />
          <mesh geometry={nodes.Material2_35.geometry} material={materials.Color_005} />
          <mesh geometry={nodes.Material2_36.geometry} material={materials.cn_scb} />
          <mesh geometry={nodes.Material2_37.geometry} material={materials.cn_rut} />
          <mesh geometry={nodes.Material3_12.geometry} material={materials.cnscf2_68} />
          <mesh geometry={nodes.Material4_11.geometry} material={materials.cnscf2_69} />
          <mesh geometry={nodes.Material2_38.geometry} material={materials.cnscf2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/camp_nou_stadium.glb')
