/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 thanos_textured_rigged.glb --transform 
Files: thanos_textured_rigged.glb [1.43MB] > /Users/yandingyin/Desktop/portfolio/public/models/thanos_textured_rigged-transformed.glb [244.36KB] (83%)
Author: CAPTAAINR (https://sketchfab.com/CAPTAAINR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/thanos-textured-rigged-ab47ab620d09404caf2dec9efdfee52d
Title: Thanos (Textured) (Rigged)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Thanos(props) {
  const { scene } = useGLTF('./models/thanos_textured_rigged-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.group_0} skeleton={nodes.Object_6.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.group_0} skeleton={nodes.Object_7.skeleton} scale={0.025} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.group_0} skeleton={nodes.Object_8.skeleton} scale={0.025} />
    </group>
  )
}

useGLTF.preload('./models/thanos_textured_rigged-transformed.glb')
